server:
  port: 7017

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://120.79.38.99:3306/pifind
    username: root
    password: zm19971205
  messages:
    basename: i18n.PlaceService
    encoding: utf-8

# 地图第三方服务
map-3rd:
  # 配置 Google API
  google:
    key: "xxxxxxx"
  # 配置高德地图 API
  amap:
    key: "xxxxxxx"
    sign:
      open: true
      key: "xxxxxxx"